### ISSUE TITLE
Add support to edit an existing item

### ISSUE THREAD

**Issue by almostjulian** [jscarle/OnePassword.NET#2]
Any chance you could add an `EditItem`  method?

**Comment by jscarle** [comment]
The syntax used by the 1Password CLI tool is a bit convoluted because of the [field assignment parameters](https://support.1password.com/command-line-reference/#how-edit-item-works). I'll have to see how I can implement internal change tracking to be able to generate a list of fields to update.

**Comment by jscarle** [comment]
Items can now be edited starting with version 2.1.0.
