### ISSUE TITLE
Add support for 1password connect api

### ISSUE THREAD

**Issue by josep-llodra** [jscarle/OnePassword.NET#50]
I am trying to mimic these steps using OnePassword.NET, but I cannot find a way of doing it.

https://developer.1password.com/docs/connect/connect-cli/

Steps that I don't know how to reproduce are the following:

* Set the OP_CONNECT_HOST and OP_CONNECT_TOKEN environment variables to your Connect instance's credentials in your production environment.
* [op run](https://developer.1password.com/docs/cli/reference/commands/run/)
* [op inject](https://developer.1password.com/docs/cli/reference/commands/inject/)
* [op read](https://developer.1password.com/docs/cli/reference/commands/read/) <-- This one I think it is already implemented in the last version using "GetSecrets" maybe?

Thank you in advance

**Comment by jscarle** [comment]
I don't have a Connect server running. If you have access to one, perhaps you could help me implement what's missing?
