### ISSUE TITLE
API Consistency 

### ISSUE THREAD

**Issue by KairuDeibisu** [jscarle/OnePassword.NET#72]
RELATED: #68 

The recent change to allow `_passwordManager.GetItem(itemId)` needs to be replicated with `_passwordManager.GetItems(vaultId)`

PS: Thanks for the swift responses.

**Comment by jscarle** [comment]
I'll take a look at this on Monday.

**Comment by jscarle** [comment]
@KairuDeibisu I just released version 2.4.0 which adds overloads to all of the methods to support IDs as strings.
