### ISSUE TITLE
The 1Password CLI executable (op.exe) was not found in folder

### ISSUE THREAD

**Issue by jrbye** [jscarle/OnePassword.NET#83]
System Details:
Windows 11
.Net 8.0.
Package Version 2.4.2

Error:
The 1Password CLI executable (op.exe) was not found in folder "C:\Users\**USER\source\repos\**SOLUTIONFOLDER\**PROJECTFOLDER\bin\Debug\net8.0"

My Code:
`var onePasswordManagerOptions = new OnePasswordManagerOptions();
var onePassword = new OnePasswordManager(onePasswordManagerOptions);`

When the One Password Manager is instantiated I am getting that the CLI executable isn't present in the build directory. I moved the op.exe file into the folder just to try it out and it is found but the password prompt comes up instead of using the account that was added with all of the account information later.

Do you have to have the One Password CLI installed for this to work? Also should I expect the login prompt to pop up?

**Comment by jrbye** [comment]
Sorry I misunderstood a few things. I didn't realize that I could put the path to the executable in the options. I did that and that part works. I also I didn't realize that using a Service Account token would negate the login. I was able to work with my 1Password admin and I now have a token and that part is working as well.

**Comment by jscarle** [comment]
Glad you worked it out! :)
